### PR TITLE
Add "capture_message" helper and request context

### PR DESCRIPTION
**Pull request by xanni**

### CODE REVIEW

**Comment by osdakira** [comment]
@xanni 
Thank you for your excellent Pull Request!
Unfortunately I can't maintain this module because I don't already use perl.

I'm going to remove this module from cpan.
However, I lost my login account, so it takes a while. 
Sorry.

**Comment by xanni** [comment]
@osdakira 
> I'm going to remove this module from cpan.
> However, I lost my login account, so it takes a while.
> Sorry.

Hopefully you can do a password recovery!  I still have a valid PAUSE account "XANNI".  Would it be possible for you to hand over the CPAN module ownership to me?

**Comment by osdakira** [comment]
@xanni 
Thank you for your account sharing.
I transferred ownership of this module to you.

Thank you for continued maintenance.
I am very grateful!

**Comment by xanni** [comment]
Thank you for your original work!

**Comment by xanni** [comment]
Pull request no longer required as it was merged and released on CPAN in 2019.

**Pull request closed without merging**
